### ISSUE TITLE
DevHub組織未認証の際に `gulp init` すると `push` の際にエラー

### ISSUE THREAD

**Issue by flectTakumiKadowaki** [FLECT-DEV-TEAM/sfdx-gulp-seed#1]
## Log

```
$ gulp init
[18:52:12] Using gulpfile ~/projects/flect/sfdx-gulp-seed/gulpfile.js
[18:52:12] Starting 'init'...
[18:52:12] Starting 'auth'...
[18:52:13] Finished 'init' after 346 ms
[18:52:32] Finished 'auth' after 20 s
[18:52:33] Starting 'create'...
[18:52:42] Finished 'create' after 9.83 s
[18:52:42] Starting 'push'...
ERROR:  You can push source only to a scratch org using this command. Use the Metadata API to sync changes for non-scratch orgs.
[18:52:45] Finished 'push' after 2.71 s
[18:52:45] Starting 'import'...
=== Import Results
REFERENCE ID  TYPE     ID
────────────  ───────  ──────────────────
account01     Account  0017F00000QXXLbQAP
account02     Account  0017F00000QXXLcQAP
account03     Account  0017F00000QXXLdQAP
account04     Account  0017F00000QXXLeQAP
account05     Account  0017F00000QXXLfQAP
[18:52:46] Finished 'import' after 773 ms
Access org 00D7F000001ux60UAA as user xxxxxxxxxx@xxxxxxxxxxxx-496877.com with the following URL: https://xxxxxxxxxxxx-496877-dev-ed.my.salesforce.com/secur/frontdoor.jsp?sid=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by endo-cariot** [comment]
> ERROR:  You can push source only to a scratch org using this command. Use the Metadata API to sync changes for non-scratch orgs.

とあるので、スクラッチ組織以外では force:source:push できないため、ソースをメタデータAPI形式に変換する必要があると思います。

- force:mdapi:convert
- force:mdapi:deploy

の組み合わせで行けるんじゃないでしょうか…（試してないですけど）

**Comment by flectTakumiKadowaki** [comment]
> スクラッチ組織以外では force:source:push できないため、ソースをメタデータAPI形式に変換する必要があると思います。

確かにスクラッチ組織以外に対しては `mdapi` を使用する必要があります。  
ただこの問題は、ScratchOrgにPushしようとしているのに、対象がScratchOrgに向いていないのが問題ですね…orz

`gulp init` タスクですが、

- DevHub 組織に認証していなければ認証
- ScratchOrgを作成
  - **この作成時点でデフォルトのScratchOrgに設定**
- ソースPush
- (以下略)

という手順になっているのですが、
**デフォルトのScratchOrgに設定**
の手順が効いていないのが原因な気がしています。

解決策としては

- ScratchOrg作成時にデフォルトの組織に設定されるよう修正
- ソースのPush時に明示的に組織を指定する

のいずれかと思っています。
